src/main/java/com/epam/pharmacy/beans/Identifiable.java
package com.epam.pharmacy.beans;

public interface Identifiable<T> {
    int getId();
}

src/main/java/com/epam/pharmacy/beans/Inquiry.java
package com.epam.pharmacy.beans;

import java.util.Objects;

public class Inquiry implements Identifiable {

    private int id;
    private int doctorId;
    private int recipeId;
    private int days;
    private InquiryStatus state;

    public Inquiry(int id, int doctorId, int recipeId, int days, InquiryStatus state) {
        this.id = id;
        this.doctorId = doctorId;
        this.recipeId = recipeId;
        this.days = days;
        this.state = state;
    }

    public Inquiry(int doctorId, int recipeId, int days) {
        this.doctorId = doctorId;
        this.recipeId = recipeId;
        this.days = days;
        state = InquiryStatus.UNDER_CONSIDERATION;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getDoctorId() {
        return doctorId;
    }

    public void setDoctorId(int doctorId) {
        this.doctorId = doctorId;
    }

    public int getRecipeId() {
        return recipeId;
    }

    public void setRecipeId(int recipeId) {
        this.recipeId = recipeId;
    }

    public InquiryStatus getState() {
        return state;
    }

    public void setState(InquiryStatus state) {
        this.state = state;
    }

    public int getDays() {
        return days;
    }

    public void setDays(int days) {
        this.days = days;
    }

    @Override
    public int getId() {
        return 0;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Inquiry inquiry = (Inquiry) o;
        return id == inquiry.id &&
                doctorId == inquiry.doctorId &&
                recipeId == inquiry.recipeId &&
                days == inquiry.days &&
                state == inquiry.state;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, doctorId, recipeId, days, state);
    }
}

src/main/java/com/epam/pharmacy/beans/InquiryStatus.java
package com.epam.pharmacy.beans;

public enum InquiryStatus {

    APPROVED("inquiry.status.approved"),
    REJECTED("inquiry.status.rejected"),
    UNDER_CONSIDERATION("inquiry.status.underConsideration");

    private String description;

    InquiryStatus(String description){
        this.description = description;
    }

    public String getDescription(){
        return description;
    }
}

src/main/java/com/epam/pharmacy/beans/MedForm.java
package com.epam.pharmacy.beans;

public enum MedForm {

    TABLETS("medicine.form.tablets"),
    SYRUP("medicine.form.syrup"),
    CREAM("medicine.form.cream"),
    GEL("medicine.form.gel"),
    DROPS("medicine.form.drops"),
    SUPPOSITORIES("medicine.form.suppositories"),
    AMPOULES("medicine.form.ampoules");

    private String description;

    MedForm(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}

src/main/java/com/epam/pharmacy/beans/Medicine.java
package com.epam.pharmacy.beans;

import java.util.Objects;

public class Medicine implements Identifiable {
    private int id;
    private String tradeName;
    private String medicineInn;
    private float price;
    private int availableAmount;
    private boolean recipeRequired;
    private MedForm form;
    private String doze;
    private String producer;
    private int amount;

    public Medicine(){}

    public Medicine(int id, String tradeName, String medicineInn, float price, int availableAmount,
                    boolean recipeRequired, MedForm form, String doze, String producer) {
        this.id = id;
        this.tradeName = tradeName;
        this.medicineInn = medicineInn;
        this.price = price;
        this.availableAmount = availableAmount;
        this.recipeRequired = recipeRequired;
        this.form = form;
        this.doze = doze;
        this.producer = producer;
    }

    public int getId() {
        return id;
    }

    public String getTradeName() {
        return tradeName;
    }

    public String getMedicineInn() {
        return medicineInn;
    }

    public float getPrice() {
        return price;
    }

    public int getAvailableAmount() {
        return availableAmount;
    }

    public boolean isRecipeRequired() {
        return recipeRequired;
    }

    public MedForm getForm() {
        return form;
    }

    public String getDoze() {
        return doze;
    }

    public String getProducer() {
        return producer;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setTradeName(String tradeName) {
        this.tradeName = tradeName;
    }

    public void setMedicineInn(String medicineInn) {
        this.medicineInn = medicineInn;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    public void setAvailableAmount(int availableAmount) {
        this.availableAmount = availableAmount;
    }

    public void setRecipeRequired(boolean recipeRequired) {
        this.recipeRequired = recipeRequired;
    }

    public void setForm(MedForm form) {
        this.form = form;
    }

    public void setDoze(String doze) {
        this.doze = doze;
    }

    public void setProducer(String producer) {
        this.producer = producer;
    }

    public int getAmount() {
        return amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Medicine medicine = (Medicine) o;
        return id == medicine.id &&
                Float.compare(medicine.price, price) == 0 &&
                availableAmount == medicine.availableAmount &&
                recipeRequired == medicine.recipeRequired &&
                amount == medicine.amount &&
                Objects.equals(tradeName, medicine.tradeName) &&
                Objects.equals(medicineInn, medicine.medicineInn) &&
                form == medicine.form &&
                Objects.equals(doze, medicine.doze) &&
                Objects.equals(producer, medicine.producer);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, tradeName, medicineInn, price, availableAmount, recipeRequired, form, doze, producer, amount);
    }
}

src/main/java/com/epam/pharmacy/beans/RecipeStatus.java
package com.epam.pharmacy.beans;

public enum RecipeStatus {

    OPEN("recipe.status.open"), CLOSED("recipe.status.closed"), EXPIRED("recipe.status.expired");

    private String description;

    private RecipeStatus(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}

src/main/java/com/epam/pharmacy/beans/SessionUser.java
package com.epam.pharmacy.beans;

import com.epam.pharmacy.dto.OrderDto;
import com.epam.pharmacy.dto.RecipeDto;
import com.epam.pharmacy.dto.InquiryDto;

import java.util.ArrayList;
import java.util.List;

public class SessionUser extends User {
    /**
     * Keeps a list of drugs that the user added to the order.
     */
    private Order order;
    /**
     * Keeps a list of drugs that found by last user search.
     */
    private List<Medicine> foundBySearch = new ArrayList<>();

    private List<RecipeDto> recipeDto = new ArrayList<>();
    private List<InquiryDto> inquiryDto = new ArrayList<>();
    private List<OrderDto> orderDto = new ArrayList<>();

    public SessionUser(User user) {
        super(user.getId(),
                user.getRole(),
                user.getName(),
                user.getSurname(),
                user.getLogin(),
                user.getPassword(),
                user.getTelephone()
        );
        order = new Order();
    }

    public Order getOrder() {
        return order;
    }

    public void setOrder(Order order) {
        this.order = order;
    }

    public List<Medicine> getFoundBySearch() {
        return foundBySearch;
    }

    public void setFoundBySearch(List<Medicine> foundBySearch) {
        this.foundBySearch = foundBySearch;
    }

    public List<RecipeDto> getRecipeDto() {
        return recipeDto;
    }

    public void setRecipeDto(List<RecipeDto> recipeDto) {
        this.recipeDto = recipeDto;
    }

    public List<InquiryDto> getInquiryDto() {
        return inquiryDto;
    }

    public void setInquiryDto(List<InquiryDto> inquiryDto) {
        this.inquiryDto = inquiryDto;
    }

    public void setOrderDto(List<OrderDto> orderDto) {
        this.orderDto = orderDto;
    }

    public List<OrderDto> getOrderDto() {
        return orderDto;
    }

    public UserRole getUserRole(){
        return super.getRole();
    }

}

src/main/java/com/epam/pharmacy/beans/UserRole.java
package com.epam.pharmacy.beans;


public enum UserRole {

    CLIENT, PHARMACIST, DOCTOR
}

src/main/java/com/epam/pharmacy/dto/InquiryDto.java
package com.epam.pharmacy.dto;

import com.epam.pharmacy.beans.Identifiable;
import com.epam.pharmacy.beans.InquiryStatus;
import com.epam.pharmacy.beans.RecipeStatus;

import java.time.LocalDate;
import java.util.Objects;

public class InquiryDto extends RecipeDto implements Identifiable {

    private int inquiryId;
    private int days;
    private InquiryStatus inquiryStatus;

    public InquiryDto(int recipeId, int inquiryId, int recipeNumber, int clientId, LocalDate validityDate, String tradeName,
                      int amount, int doctorId, RecipeStatus status, String medicineInn, int notRedeemed,
                      int days, InquiryStatus inquiryStatus) {
        super(recipeId, clientId, recipeNumber, validityDate, tradeName, amount, doctorId, status, medicineInn, notRedeemed);
        this.inquiryId = inquiryId;
        this.days = days;
        this.inquiryStatus = inquiryStatus;
    }

    public InquiryDto(int recipeId, int inquiryId, int recipeNumber, int clientId, LocalDate validityDate, String tradeName, int amount, int notRedeemed, int days, InquiryStatus inquiryStatus) {
        super(recipeId, recipeNumber, clientId, validityDate, tradeName, amount, notRedeemed);
        this.inquiryId = inquiryId;
        this.days = days;
        this.inquiryStatus = inquiryStatus;
    }

    public int getDays() {
        return days;
    }

    public void setDays(int days) {
        this.days = days;
    }

    public InquiryStatus getInquiryStatus() {
        return inquiryStatus;
    }

    @Override
    public String getTradeName() {
        return super.getTradeName();
    }

    @Override
    public int getAmount() {
        return super.getAmount();
    }

    @Override
    public int getId() {
        return inquiryId;
    }

    @Override
    public int getNumber() {
        return super.getNumber();
    }

    @Override
    public int getNotRedeemed() {
        return super.getNotRedeemed();
    }

    @Override
    public int getRecipeId() {
        return super.getRecipeId();
    }

    public void setInquiryStatus(InquiryStatus inquiryStatus) {
        this.inquiryStatus = inquiryStatus;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        InquiryDto that = (InquiryDto) o;
        return days == that.days &&
                inquiryStatus == that.inquiryStatus;
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), days, inquiryStatus);
    }
}

src/main/java/com/epam/pharmacy/dto/OrderDto.java
package com.epam.pharmacy.dto;

import com.epam.pharmacy.beans.Identifiable;
import com.epam.pharmacy.beans.Order;

import java.time.LocalDate;

public class OrderDto extends Order implements Identifiable {

    private String tradeName;
    private int amount;

    public OrderDto(int number, LocalDate date, float totalPrice, boolean isOpen, String tradeName, int amount){
        super(number, date, totalPrice, isOpen);
        this.tradeName = tradeName;
        this.amount = amount;
    }

    public int getAmount() {
        return amount;
    }

    public String getTradeName() {
        return tradeName;
    }

    public int getNumber() {
        return super.getId();
    }

    public boolean getIsOpen() {
        return super.isOpen();
    }

    @Override
    public LocalDate getDate() {
        return super.getDate();
    }

    @Override
    public float getTotalPrice() {
        return super.getTotalPrice();
    }

    @Override
    public int getId() {
        return super.getId();
    }

}

src/main/java/com/epam/pharmacy/dto/RecipeDto.java
package com.epam.pharmacy.dto;

import com.epam.pharmacy.beans.Identifiable;
import com.epam.pharmacy.beans.Recipe;
import com.epam.pharmacy.beans.RecipeStatus;

import java.time.LocalDate;

public class RecipeDto extends Recipe implements Identifiable {

    private int id;
    private String tradeName;
    private String medicineInn;
    private int amount;
    private int doctorId;
    private int notRedeemed;

    public RecipeDto(int recipeId, int clientId, int recipeNumber, LocalDate validityDate, String tradeName, int amount,
                     int doctorId, RecipeStatus status, String medicineInn, int notRedeemed) {
        super (recipeId, clientId, recipeNumber, validityDate, doctorId, status);
        this.tradeName = tradeName;
        this.amount = amount;
        this.medicineInn = medicineInn;
        this.notRedeemed = notRedeemed;

    }

    /*package-private*/ RecipeDto(int recipeId, String tradeName, int amount, int notRedeemed) {
        super(recipeId);
        this.tradeName = tradeName;
        this.amount = amount;
        this.notRedeemed = notRedeemed;
    }

    public RecipeDto(int recipeId, int recipeNumber, int clientId, LocalDate validityDate, String tradeName, int amount, int notRedeemed) {
        super(recipeId, recipeNumber, clientId, validityDate);
        this.tradeName = tradeName;
        this.notRedeemed =  notRedeemed;
    }

    public int getRecipeId(){
        return super.getRecipeId();
    }

    public int getRecipeNumber(){
        return super.getNumber();
    }

    public RecipeStatus getRecipeStatus(){
        return super.getStatus();
    }

    public String getTradeName() {
        return tradeName;
    }

    public String getMedicineInn() {
        return medicineInn;
    }

    public int getNotRedeemed() {
        return notRedeemed;
    }

    public int getAmount() {
        return amount;
    }


    @Override
    public int getId() {
        return super.getId();
    }

}

src/main/java/com/epam/pharmacy/servlet/Servlet.java
package com.epam.pharmacy.servlet;


import com.epam.pharmacy.command.Command;
import com.epam.pharmacy.command.CommandFactory;
import com.epam.pharmacy.exceptions.CommandException;
import com.epam.pharmacy.exceptions.ServiceException;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

import static com.epam.pharmacy.Constants.ERROR_JSP;
import static com.epam.pharmacy.Constants.KEY_ERROR_MESSAGE;
import static com.epam.pharmacy.Constants.PARAMETER_COMMAND;
import static com.epam.pharmacy.Constants.VALUE_APPLICATION_ERROR;

@WebServlet(name = "Servlet", urlPatterns = {"/Servlet", "/login", "/registration", "/changeLanguage", "/pharmacist"})
public class Servlet extends HttpServlet {

    private static final Logger LOG = LogManager.getLogger(Servlet.class);

    public void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        process(request, response);
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        process(request, response);
    }

    public void process(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String command = request.getParameter(PARAMETER_COMMAND);
        String page = null;
        try {
            Command action = CommandFactory.create(command);
            action.init();
            page = action.execute(request, response);
            action.done();
        } catch (CommandException | ServiceException e) {
            LOG.error(VALUE_APPLICATION_ERROR + e.getMessage(), e);
            request.setAttribute(KEY_ERROR_MESSAGE, VALUE_APPLICATION_ERROR);
            RequestDispatcher dispatcher = request.getRequestDispatcher(ERROR_JSP);
            dispatcher.forward(request, response);
        }

        if (page != null) {
            RequestDispatcher dispatcher = request.getRequestDispatcher(page);
            dispatcher.forward(request, response);
        }
    }
}

src/main/webapp/doctor_page.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" isELIgnored="false" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ include file="WEB-INF/jsp/fragment/Variables.jspf" %>

<c:set var="page" value="doctor_page.jsp" scope="session"/>
<c:set var="role" value="${sessionScope.user.userRole}"/>
<c:if test="${role ne 'DOCTOR'}">
    <jsp:forward page="index.jsp"/>
</c:if>

<html lang="${language}">
<head>
    <title>User page</title>
    <link rel="stylesheet" href="css/user_page.css" />
    <link rel="stylesheet" href="css/header_footer.css"/>
</head>

<body>
<div style="height: 90%" class="main_container">
    <jsp:include page="WEB-INF/jsp/common_header.jsp"/>
    <div style="height: 85%" class="inner_container">
        <form action="login" method="post">
            <div class="my_account"><h1><fmt:message key="header.doctorAccount"/></h1>
                <hr/>
                <div class="under_line">
                    <div><fmt:message key="header.myRecipes"/></div>
                    <div class="container">
                        <fmt:message key="header.myInquiries"/>
                        <table>
                            <tr>
                                <th>
                                    <fmt:message key="header.recipeId"/>
                                </th>
                                <th>
                                    <fmt:message key="header.tradeName"/>
                                </th>
                                <th>
                                    <fmt:message key="header.amount"/>
                                </th>
                                <th>
                                    <fmt:message key="header.notRedeemed"/>
                                </th>
                                <th>
                                    <fmt:message key="header.forHowManyDays"/>
                                </th>
                                <th>
                                    <fmt:message key="header.inquiryStatus"/>
                                </th>
                            </tr>
                            <c:forEach items="${sessionScope.user.inquiryDto}" var="inquiryDto">
                                <tr>
                                    <c:set var="status" value="${inquiryDto.getInquiryStatus()}"/>
                                    <td align="center">${inquiryDto.getRecipeId()}</td>
                                    <td align="center">${inquiryDto.getTradeName()}</td>
                                    <td align="center">${inquiryDto.getAmount()}</td>
                                    <td align="center">${inquiryDto.getNotRedeemed()}</td>
                                    <td align="center">${inquiryDto.getDays()}</td>
                                    <c:set var="description" value="${inquiryDto.inquiryStatus.description}" />
                                    <td align="center"><fmt:message key="${description}"/></td>
                                </tr>
                            </c:forEach>
                        </table>
                    </div>
                    <div><fmt:message key="header.accountDetails"/>
                        <br/><br/>
                        <p>${sessionScope.user.name}<p>
                        <p>${sessionScope.user.surname}<p>
                        <p>${sessionScope.user.telephone}<p>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div><jsp:include page="html/footer.html"/></div>
</div>
</body>
</html>

src/main/webapp/error.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" isELIgnored="false" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ include file="WEB-INF/jsp/fragment/Variables.jspf" %>

<c:set var="page" value="error.jsp" scope="session"/>

<html lang="${language}">
<head>
    <title>Error Page</title>
    <link rel="stylesheet" href="css/error.css">
    <link rel="stylesheet" href="css/header_footer.css">
</head>
<body>
<div class="main_container">
    <jsp:include page="WEB-INF/jsp/common_header.jsp"/>
    <div class="container">
      <h1><fmt:message key="${errorMsg}"/></h1>
    </div>
    <div>
        <jsp:include page="html/footer.html"/>
    </div>
</div>
</body>
</html>

src/main/webapp/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" isELIgnored="false" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ include file="WEB-INF/jsp/fragment/Variables.jspf" %>

<c:set var="page" value="index.jsp" scope="session"/>

<html>
<head>
    <title>Pharmacy</title>
    <link rel="stylesheet" href="css/index.css"/>
    <link rel="stylesheet" href="css/header_footer.css"/>
</head>

<body>
<div class="main_container">
    <jsp:include page="WEB-INF/jsp/common_header.jsp"/>
    <c:choose>
        <c:when test="${sessionScope.user == null}">
            <form action="login" method="post">
                <div class="container">
                    <!-- login -->
                    <div data-label="login">
                        <p><input class="text_field" type="text" name="login"
                                  value=""
                                  placeholder="<fmt:message key="login.userName"/>"/>
                        </p>
                    </div>
                    <!-- password -->
                    <div data-label="password">
                        <p><input class="text_field"
                                  type="password"
                                  name="password"
                                  value=""
                                  placeholder="<fmt:message key="login.password"/>"/>
                        </p>
                    </div>
                    <!-- submit button -->
                    <div>
                        <input class="login_button" type="submit" value="<fmt:message key="action.logIn"/>"/><br/>
                        <input type="hidden" value="logIn" name="command"/>
                    </div>
                    <div class="errorMessage">
                        <c:if test="${errorMsg ne null}">
                            <b><fmt:message key="${errorMsg}"/></b>
                        </c:if>
                    </div>
                    <div class="message">
                        <c:if test="${inviteMessage ne null}">
                            <b><fmt:message key="${inviteMessage}"/></b>
                        </c:if>
                    </div>
                </div>
            </form>
        </c:when>
        <c:otherwise>
            <div class="home-container">
                <div id="welcome"><b>Welcome to the pharmacy</b></div>
            </div>
        </c:otherwise>
    </c:choose>
    <jsp:include page="html/footer.html"/>
</div>
</body>
</html>

src/main/webapp/pharmacist_page.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" isELIgnored="false" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ include file="WEB-INF/jsp/fragment/Variables.jspf" %>

<c:set var="page" value="pharmacist_page.jsp" scope="session"/>
<c:set var="role" value="${sessionScope.user.userRole}"/>
<c:if test="${role ne 'PHARMACIST'}">
    <jsp:forward page="index.jsp"/>
</c:if>

<html>
<head>
    <title>Pharmacist</title>
    <link rel="stylesheet" href="css/user_page.css"/>
    <link rel="stylesheet" href="css/header_footer.css"/>
</head>

<body>
<div class="main_container">
    <jsp:include page="WEB-INF/jsp/common_header.jsp"/>
    <div style="height: 700px" class="inner_container">
        <form action="pharmacist" method="post">
            <div class="my_account"><h1><fmt:message key="header.pharmacistAccount"/></h1>
                <hr/>
                <div class="under_line">
                    <div><fmt:message key="header.medicineList"/>
                        <table>
                            <tr>
                                <th>N</th>
                                <th><fmt:message key="header.tradeName"/></th>
                                <th><fmt:message key="header.INN"/></th>
                                <th><fmt:message key="header.doze"/></th>
                                <th><fmt:message key="header.form"/></th>
                                <th><fmt:message key="header.producer"/></th>
                                <th><fmt:message key="header.price"/></th>
                                <th><fmt:message key="header.amount"/></th>
                            </tr>
                            <c:forEach items="${requestScope.medicineList}" var="medicine">
                                <tr>
                                    <td>${medicine.id}</td>
                                    <td>${medicine.tradeName}</td>
                                    <td>${medicine.medicineInn}</td>
                                    <td>${medicine.doze}</td>
                                    <c:set var="form" value="${medicine.form.description}"/>
                                    <td><fmt:message key="${form}"/></td>
                                    <td>${medicine.producer}</td>
                                    <td>${medicine.price}</td>
                                    <td>${medicine.availableAmount}</td>
                                </tr>
                            </c:forEach>
                        </table>
                    </div>
                    <div><fmt:message key="header.accountDetails"/>
                        <br/><br/>
                        <p>${sessionScope.user.name}</p>
                        <p>${sessionScope.user.surname}</p>
                        <p>${sessionScope.user.telephone}</p>
                        <br/><br/>
                        <hr/>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div>
        <jsp:include page="html/footer.html"/>
    </div>
</div>
</body>
</html>

src/main/webapp/recipe_history.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" isELIgnored="false" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ include file="WEB-INF/jsp/fragment/Variables.jspf" %>

<c:set var="page" value="recipe_history.jsp" scope="session"/>
<jsp:include page="WEB-INF/jsp/roleChecker.jsp"/>

<html>
<head>
    <title>Order history</title>
    <link rel="stylesheet" href="css/user_page.css">
    <link rel="stylesheet" href="css/header_footer.css">
</head>
<body>
<div class="main_container">
    <jsp:include page="WEB-INF/jsp/common_header.jsp"/>
    <div style="height: 85%" class="inner_container">
        <div class="my_account"><h1><fmt:message key="header.myRecipes"/></h1><br/>
            <h2><c:out value="${message}"/></h2>
            <hr/>
        </div>
        <div class="container">
            <fmt:message key="header.myRecipes"/>
            <table>
                <tr>
                    <th>
                        <fmt:message key="header.recipeNumber"/>
                    </th>
                    <th>
                        <fmt:message key="header.tradeName"/>
                    </th>
                    <th>
                        <fmt:message key="header.amount"/>
                    </th>
                    <th>
                        <fmt:message key="header.validityDate"/>
                    </th>
                    <th>
                        <fmt:message key="header.notRedeemed"/>
                    </th>
                    <th>
                        <fmt:message key="header.state"/>
                    </th>
                </tr>
                <c:forEach items="${sessionScope.user.recipeDto}" var="recipeDto">
                    <tr>
                        <td align="center">${recipeDto.recipeNumber}</td>
                        <td align="center">${recipeDto.tradeName}</td>
                        <td align="center">${recipeDto.amount}</td>
                        <td align="center">${recipeDto.validityDate}</td>
                        <td align="center">${recipeDto.notRedeemed}</td>
                        <c:set var="description" value="${recipeDto.recipeStatus.description}"/>
                        <td align="center"><fmt:message key="${description}"/></td>
                    </tr>
                </c:forEach>
            </table>
        </div>
        <br/>
        <div id="a">
            <a class="on_page" href="write_doctor.jsp"><b><fmt:message key="link.writeToDoctor"/></b></a>
        </div>
    </div>
</div>

<div>
    <jsp:include page="html/footer.html"/>
</div>
</body>
</html>

src/main/webapp/search.jsp
<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" language="java" isELIgnored="false" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ include file="WEB-INF/jsp/fragment/Variables.jspf" %>

<c:set var="page" value="search.jsp" scope="session"/>
<jsp:include page="WEB-INF/jsp/roleChecker.jsp"/>

<html>
<head>
    <title>Search</title>
    <link rel="stylesheet" href="css/search.css"/>
    <link rel="stylesheet" href="css/header_footer.css"/>
</head>
<body>

<div class="main_container">
    <jsp:include page="WEB-INF/jsp/common_header.jsp"/>
    <div class="container">
        <form action="Servlet" method="post">
            <div id="search"><fmt:message key="header.SEARCH"/></div>
            <div><input class="search_field" type="search" name="search" value=""
                        placeholder="<fmt:message key="text.paracetamol"/>"/>
                <input class="search_button" type="submit" value="<fmt:message key="action.search"/>"/>
                <input type="hidden" value="search" name="command"/>
            </div>
            <c:if test="${message ne null}">
                <div class="errorMessage">
                    <h3><fmt:message key="${message}"/></h3>
                </div>
            </c:if>
        </form>
    </div>
    <div>
        <jsp:include page="html/footer.html"/>
    </div>
</div>
</body>
</html>